package telemarketer.skittlealley.persist.mybatis.domain;

public class DrawWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_word.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_word.word
     *
     * @mbg.generated
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_word.word_tip
     *
     * @mbg.generated
     */
    private String wordTip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_word.id
     *
     * @return the value of draw_word.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    public DrawWord withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_word.id
     *
     * @param id the value for draw_word.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_word.word
     *
     * @return the value of draw_word.word
     * @mbg.generated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    public DrawWord withWord(String word) {
        this.setWord(word);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_word.word
     *
     * @param word the value for draw_word.word
     * @mbg.generated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_word.word_tip
     *
     * @return the value of draw_word.word_tip
     * @mbg.generated
     */
    public String getWordTip() {
        return wordTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    public DrawWord withWordTip(String wordTip) {
        this.setWordTip(wordTip);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_word.word_tip
     *
     * @param wordTip the value for draw_word.word_tip
     * @mbg.generated
     */
    public void setWordTip(String wordTip) {
        this.wordTip = wordTip == null ? null : wordTip.trim();
    }
}