druid:
  options: autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
  initialSize: 10
  minIdle: 5
  maxActive: 100
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT '1'
  testWhileIdle: true
  testOnBorrow: true
  testOnReturn: false