/*
 * This file is generated by jOOQ.
 */
package telemarketer.skittlealley.persist.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.9"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DrawWord implements Serializable {

    private static final long serialVersionUID = -671118863;

    private Integer id;
    private String word;
    private String wordTip;

    public DrawWord() {
    }

    public DrawWord(DrawWord value) {
        this.id = value.id;
        this.word = value.word;
        this.wordTip = value.wordTip;
    }

    public DrawWord(
            Integer id,
            String word,
            String wordTip
    ) {
        this.id = id;
        this.word = word;
        this.wordTip = wordTip;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWord() {
        return this.word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getWordTip() {
        return this.wordTip;
    }

    public void setWordTip(String wordTip) {
        this.wordTip = wordTip;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DrawWord (");

        sb.append(id);
        sb.append(", ").append(word);
        sb.append(", ").append(wordTip);

        sb.append(")");
        return sb.toString();
    }
}
