server:
  port: 9607
spring:
  webflux:
    static-path-pattern: /**
    format:
      date: iso
  profiles:
    active: production
  web:
    resources:
      static-locations: classpath:/dist/
logging:
  config: classpath:logback-${spring.profiles.active}.xml