/*
 * This file is generated by jOOQ.
 */
package telemarketer.skittlealley.persist;


import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import telemarketer.skittlealley.persist.tables.DrawWordTable;
import telemarketer.skittlealley.persist.tables.records.DrawWordRecord;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.9"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DrawWordRecord, Integer> IDENTITY_DRAW_WORD = Identities0.IDENTITY_DRAW_WORD;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DrawWordRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;
    public static final UniqueKey<DrawWordRecord> CONSTRAINT_B0 = UniqueKeys0.CONSTRAINT_B0;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DrawWordRecord, Integer> IDENTITY_DRAW_WORD = Internal.createIdentity(DrawWordTable.DRAW_WORD, DrawWordTable.DRAW_WORD.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DrawWordRecord> CONSTRAINT_B = Internal.createUniqueKey(DrawWordTable.DRAW_WORD, "CONSTRAINT_B", DrawWordTable.DRAW_WORD.ID);
        public static final UniqueKey<DrawWordRecord> CONSTRAINT_B0 = Internal.createUniqueKey(DrawWordTable.DRAW_WORD, "CONSTRAINT_B0", DrawWordTable.DRAW_WORD.WORD);
    }
}
