/*
 * This file is generated by jOOQ.
 */
package telemarketer.skittlealley.persist;


import telemarketer.skittlealley.persist.tables.DrawWordTable;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.9"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>PUBLIC.DRAW_WORD</code>.
     */
    public static final DrawWordTable DRAW_WORD = DrawWordTable.DRAW_WORD;
}
