DROP TABLE draw_word
IF EXISTS;
CREATE TABLE draw_word (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  word       VARCHAR(255),
  word_count SMALLINT,
  word_type  VARCHAR(255),
  PRIMARY KEY (id)
);