package telemarketer.skittlealley.persist.mybatis.dao;

import org.apache.ibatis.annotations.Param;
import telemarketer.skittlealley.persist.mybatis.domain.DrawWord;
import telemarketer.skittlealley.persist.mybatis.domain.DrawWordExample;

import java.util.List;

public interface DrawWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    long countByExample(DrawWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    int deleteByExample(DrawWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    int insert(DrawWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    int insertSelective(DrawWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    DrawWord selectOneByExample(DrawWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    List<DrawWord> selectByExample(DrawWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    DrawWord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DrawWord record, @Param("example") DrawWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DrawWord record, @Param("example") DrawWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DrawWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_word
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DrawWord record);
}